// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UIWeb.Models;

#nullable disable

namespace UIWeb.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250408133208_initWithData")]
    partial class initWithData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "HTML bir işaretleme dilidir.",
                            Title = "HTML"
                        },
                        new
                        {
                            Id = 2,
                            Content = "CSS bir işaretleme dilidir ve HTML etiketlerine görsellik eklemek için kullanılır.",
                            Title = "CSS"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Javascript bir programlama dilidir. HTML ve CSS ile oluşturulmuş sayfalara etkileşim ve hareket katmak için kullanılır.",
                            Title = "Javascript"
                        },
                        new
                        {
                            Id = 4,
                            Content = "C# geniş kapsamlı bir programlama dilidir. İnternet siteleri, Windows uygulamaları veya oyunları yapmak için sıkça kullanılır.",
                            Title = "C#"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
